FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY pyproject.toml uv.lock* ./
RUN uv sync --no-cache

COPY . .

EXPOSE 8000

CMD ["uv", "run", "python", "-m", "uvicorn", "proj.asgi:application", "--host", "0.0.0.0", "--port", "8000"]