FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY pyproject.toml uv.lock* ./
RUN uv sync --no-cache

COPY . .

CMD ["uv", "run", "python", "-m", "celery", "-A", "proj", "worker", "-l", "info", "--pool", "gevent"]