# Generated by Django 5.2.4 on 2025-08-12 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='링크 모음 제목')),
                ('description', models.TextField(blank=True, verbose_name='링크 모음 설명')),
                ('is_public', models.BooleanField(default=False, verbose_name='링크 모음 공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_uuid', models.UUIDField(null=True, verbose_name='링크 모음 공유 링크 UUID')),
                ('expire_date', models.DateTimeField(null=True, verbose_name='링크 모음 공유 링크 만료 기간')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='링크 모음 소유자')),
            ],
            options={
                'verbose_name': '링크 모음',
                'verbose_name_plural': '링크 모음 목록',
                'db_table': 'link_collections',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='링크 제목')),
                ('url', models.URLField(max_length=256, verbose_name='링크 URL')),
                ('description', models.TextField(blank=True, verbose_name='링크 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='myapp.linkcollection', verbose_name='링크가 포함된 컬렉션')),
            ],
            options={
                'verbose_name': '링크',
                'verbose_name_plural': '링크 목록',
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='즐겨찾기 소유자')),
                ('collections', models.ManyToManyField(related_name='bookmarks', to='myapp.linkcollection', verbose_name='포함된 링크 모음들')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기 목록',
                'db_table': 'bookmarks',
            },
        ),
    ]
