# Generated by Django 5.2.4 on 2025-08-17 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_linkcollectionlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCollectionViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myapp.linkcollection', verbose_name='조회한 링크 모음')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='조회한 사용자')),
            ],
            options={
                'verbose_name': '조회',
                'verbose_name_plural': '조회 목록',
                'db_table': 'link_collection_view',
                'constraints': [models.UniqueConstraint(fields=('collection', 'viewer'), name='unique_collection_viewer')],
            },
        ),
    ]
