# Generated by Django 5.2.4 on 2025-08-21 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_linkcollectionviewmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=256, null=True, verbose_name='아바타 CloudFront URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL, verbose_name='아바타 소유자')),
            ],
            options={
                'verbose_name': '사용자 아바타',
                'verbose_name_plural': '사용자 아바타 목록',
                'db_table': 'user_avatars',
            },
        ),
    ]
