# Generated by Django 5.2.4 on 2025-08-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_useravatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCollectionThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=256, null=True, verbose_name='썸네일 URL')),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='myapp.linkcollection', verbose_name='썸네일 컬렉션')),
            ],
            options={
                'verbose_name': '링크 모음 썸네일',
                'verbose_name_plural': '링크 모음 썸네일 목록',
                'db_table': 'link_collection_thumbnail',
            },
        ),
    ]
