# Generated by Django 5.2.4 on 2025-09-11 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_linkcollectionthumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcollection',
            name='share_uuid',
            field=models.UUIDField(db_index=True, null=True, verbose_name='링크 모음 공유 링크 UUID'),
        ),
        migrations.AddIndex(
            model_name='linkcollection',
            index=models.Index(fields=['owner'], name='link_collec_owner_i_9aed13_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcollection',
            index=models.Index(fields=['is_public'], name='link_collec_is_publ_134a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcollection',
            index=models.Index(fields=['-created_at'], name='link_collec_created_8d0226_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcollectionviewmodel',
            index=models.Index(fields=['viewer', 'collection'], name='link_collec_viewer__8d491d_idx'),
        ),
    ]
