# Generated by Django 5.2.4 on 2025-09-11 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_linkcollection_share_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcollection',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='링크 모음 좋아요 개수'),
        ),
        migrations.AddField(
            model_name='linkcollection',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='링크 모음 조회 수'),
        ),
        migrations.AddIndex(
            model_name='linkcollection',
            index=models.Index(fields=['-likes_count'], name='link_collec_likes_c_e8c226_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcollection',
            index=models.Index(fields=['-views_count'], name='link_collec_views_c_6230d0_idx'),
        ),
    ]
